#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# env_present KEY — true when KEY exists and has a non-empty value in .env.
env_present() {
  local value
  value=$(_existing "$1" || true)
  [[ -n "$value" ]]
}

# skip_stage "Name" "KEY[,KEY...]" — preserve progress while skipping a
# completed setup stage. Optional values are intentionally not listed.
skip_stage() {
  local name="$1" keys="$2"
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$name" "$RESET"
  say "检测到 .env 已有 $keys，跳过本阶段；如需修改请直接编辑 .env 后重新运行。"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PROJECT_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd)
cd "$PROJECT_DIR"
ENV_FILE="${ENV_FILE:-$PROJECT_DIR/.env}"

# ensure_node — Git Bash can find npm while npm's child processes cannot find
# node. Add common Windows installation locations before invoking npm scripts.
ensure_node() {
  if command -v node >/dev/null 2>&1; then
    node --version >/dev/null 2>&1 && return 0
  fi
  local candidate
  for candidate in \
    "/c/Program Files/nodejs" \
    "/c/Program Files (x86)/nodejs" \
    "/c/Users/${USERNAME:-unknown}/AppData/Local/Programs/nodejs"; do
    if [[ -x "$candidate/node.exe" ]]; then
      PATH="$candidate:$PATH"
      export PATH
      hash -r
      node --version >/dev/null 2>&1 && return 0
    fi
  done
  warn "找不到 Node.js。请安装 Node.js 22.19+，重新打开 Git Bash 后再运行向导。"
  return 1
}

banner "nib 本地配置"

if env_present NAPCAT_WS_URL; then
  skip_stage "NapCat — 安装与 QQ 登录" "NAPCAT_WS_URL"
else
  stage "NapCat — 安装与 QQ 登录"
  say "先确保 NapCat 已安装，并登录用于监听群聊的 QQ 账号。"
  open_url "https://napneko.github.io/guide/install"
  step "启动 NapCat；按照启动日志给出的 WebUI 地址打开管理页面。"
  step "在 WebUI 的 QQ 登录页面扫码登录。"
  pause "看到 NapCat 与 QQ 均在线后，按 Enter 继续。"
fi

if env_present NAPCAT_WS_URL; then
  skip_stage "NapCat — 正向 WebSocket" "NAPCAT_WS_URL"
else
  say "nib 作为客户端连接 NapCat 的 WebSocket 服务器。"
  open_url "https://napneko.github.io/config/basic"
  step "WebUI → 网络配置 → 新建 → WebSocket 服务器（正向 WS）。"
  step "建议 host=127.0.0.1、port=3001、messagePostFormat=array，并启用保存。"
  step "可设置一个访问 token；它与 WebUI 登录密码不是同一个值。"
  ask NAPCAT_WS_URL "WebSocket 地址 [建议 ws://127.0.0.1:3001]："
  NAPCAT_WS_URL="${NAPCAT_WS_URL:-ws://127.0.0.1:3001}"
  ask_secret NAPCAT_ACCESS_TOKEN "NapCat WebSocket token（未设置可直接 Enter）："
  write_env NAPCAT_WS_URL "$NAPCAT_WS_URL"
  write_env NAPCAT_ACCESS_TOKEN "$NAPCAT_ACCESS_TOKEN"
fi

if env_present QQ_GROUP_IDS; then
  skip_stage "QQ — 群白名单" "QQ_GROUP_IDS"
else
  say "指定群全员采集；非指定群不会保存。"
  ask QQ_GROUP_IDS "要监听的群号（多个用英文逗号分隔）："
  while [[ ! "$QQ_GROUP_IDS" =~ ^[0-9]+(,[0-9]+)*$ ]]; do
    warn "请输入纯数字群号；多个 ID 之间不要加空格。"
    ask QQ_GROUP_IDS "群号："
  done
  FIRST_GROUP_ID="${QQ_GROUP_IDS%%,*}"
  ask QQ_GROUP_NAME "第一个群（$FIRST_GROUP_ID）的显示名称（可留空）："
  if [[ -n "$QQ_GROUP_NAME" ]]; then
    QQ_GROUP_NAMES=$(QQ_GROUP_ID="$FIRST_GROUP_ID" QQ_GROUP_NAME="$QQ_GROUP_NAME" node -e \
      'process.stdout.write(JSON.stringify({[process.env.QQ_GROUP_ID]: process.env.QQ_GROUP_NAME}))')
  else
    QQ_GROUP_NAMES="{}"
  fi
  write_env QQ_GROUP_IDS "$QQ_GROUP_IDS"
  write_env QQ_GROUP_NAMES "$QQ_GROUP_NAMES"
fi

if env_present DEEPSEEK_API_KEY; then
  skip_stage "DeepSeek — 模型凭据" "DEEPSEEK_API_KEY"
else
  say "pi SDK 将用这个密钥运行晚报整理 agent。"
  open_url "https://platform.deepseek.com/api_keys"
  step "登录后创建一个 API Key，并立即复制；平台通常不会再次完整显示。"
  ask_secret DEEPSEEK_API_KEY "粘贴 DeepSeek API Key："
  while [[ -z "$DEEPSEEK_API_KEY" ]]; do
    warn "DeepSeek API Key 不能为空。"
    ask_secret DEEPSEEK_API_KEY "粘贴 DeepSeek API Key："
  done
  write_env DEEPSEEK_API_KEY "$DEEPSEEK_API_KEY"
  write_env PI_MODEL "deepseek-v4-pro"
fi

if env_present TELEGRAM_BOT_TOKEN; then
  skip_stage "Telegram — 创建 bot" "TELEGRAM_BOT_TOKEN"
else
  say "BotFather 会创建用于接收晚报的 Telegram bot。"
  open_url "https://t.me/botfather"
  step "向 @BotFather 发送 /newbot，依次设置显示名称和以 bot 结尾的用户名。"
  step "复制 BotFather 返回的 token；它类似 123456:ABC...，请按密码保管。"
  ask_secret TELEGRAM_BOT_TOKEN "粘贴 Telegram bot token："
  while [[ ! "$TELEGRAM_BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]]; do
    warn "token 格式不正确，请重新从 BotFather 复制。"
    ask_secret TELEGRAM_BOT_TOKEN "Telegram bot token："
  done
  write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
fi

if env_present TELEGRAM_CHAT_ID; then
  skip_stage "Telegram — 获取私聊 Chat ID" "TELEGRAM_CHAT_ID"
else
  say "必须先与 bot 建立私聊，Telegram 才会在 getUpdates 中返回 chat ID。"
  step "打开刚创建的 bot，点击 Start 或发送 /start。"
  pause "消息发送完成后，按 Enter 让向导读取最近更新。"
  TELEGRAM_UPDATES=$(curl --fail --silent --show-error \
    "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getUpdates")
  TELEGRAM_CHAT_ID=$(TELEGRAM_UPDATES="$TELEGRAM_UPDATES" node -e '
    const payload = JSON.parse(process.env.TELEGRAM_UPDATES);
    const chats = (payload.result || [])
      .map((update) => update.message?.chat ?? update.edited_message?.chat)
      .filter((chat) => chat?.type === "private" && (typeof chat.id === "number" || typeof chat.id === "string"));
    if (chats.length) process.stdout.write(String(chats.at(-1).id));
  ')
  if [[ -z "$TELEGRAM_CHAT_ID" ]]; then
    warn "没有找到私聊更新。确认已向 bot 发送 /start，然后手动输入 chat ID。"
    ask TELEGRAM_CHAT_ID "Telegram 私聊 Chat ID："
  fi
  while [[ ! "$TELEGRAM_CHAT_ID" =~ ^-?[0-9]+$ ]]; do
    warn "Chat ID 必须是数字。"
    ask TELEGRAM_CHAT_ID "Telegram 私聊 Chat ID："
  done
  write_env TELEGRAM_CHAT_ID "$TELEGRAM_CHAT_ID"
fi

stage "本地验证"
if env_present DATA_DIR; then
  note "检测到 DATA_DIR，保留现有值。"
else
  write_env DATA_DIR "./data"
fi
if env_present MAX_AGENT_TOOL_CALLS; then
  note "检测到 MAX_AGENT_TOOL_CALLS，保留现有值。"
else
  write_env MAX_AGENT_TOOL_CALLS "20"
fi
say "安装依赖并检查本地代码；这一步不会调用 DeepSeek 或发送 Telegram 消息。"
ensure_node
# npm on Windows normally runs package scripts through cmd.exe. In Git Bash
# that child shell can lose the MSYS Node path, so keep package scripts in the
# same shell where `node` was verified.
export npm_config_script_shell="${npm_config_script_shell:-/bin/bash}"
npm install
npm run check
npm test
say "配置与离线检查已完成。"
note "启动命令：npm run dev"
warn "npm run dev 会连接 NapCat，并持续占用当前终端；关闭或休眠电脑会停止收集消息。"

finish
